#!/usr/bin/python
import sys

sys.path.append('/usr/share/reddo/')

try:
    from reddolib.Reddo import Reddo
except ImportError, e:
    print >>sys.stderr, "Unable to import reddo library:", e
    sys.exit()

reddo = Reddo()
print reddo.translate()

# vim:ts=4 sts=4 tw=79 expandtab:

